import { HashMap } from "./hash_map.js";

const test = new HashMap()

test.set('apple', 'red')
test.set('banana', 'yellow')
test.set('carrot', 'orange')
test.set('dog', 'brown')
test.set('elephant', 'gray')
test.set('frog', 'green')
test.set('grape', 'purple')
test.set('hat', 'black')
test.set('ice cream', 'white')
test.set('jacket', 'blue')
test.set('kite', 'pink')
test.set('lion', 'golden')

console.log(test.get('kite'))
console.log(test.has('jacket'))
console.log(test.keys())
console.log(test.values())
console.log(test.entries())
test.set('kite', 'red')
console.log(test.entries())
console.log(test.length())
test.set('moon', 'silver')
test.set('sun', 'yellow')
console.log(test.length())
console.log(test.entries())